services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: selfplus-db
      POSTGRES_USER: selfplus
      POSTGRES_PASSWORD: selfplus
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: ./demo
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/selfplus-db
      SPRING_DATASOURCE_USERNAME: selfplus
      SPRING_DATASOURCE_PASSWORD: selfplus
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres-data:
